---
abstract: 'Delay setup of application scoped Catalyst Components'
author:
  - 'John Napiorkowski <jjnapiork@cpan.org>'
build_requires:
  Catalyst::Test: '0'
  Test::Most: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.032, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Catalyst-Component-WithDelayedSetup
requires:
  Moose: '2.1403'
resources:
  bugtracker: https://github.com/jjn1056/Catalyst-Component-WithDelayedSetup/issues
  homepage: https://github.com/jjn1056/Catalyst-Component-WithDelayedSetup
  repository: https://github.com/jjn1056/Catalyst-Component-WithDelayedSetup.git
version: '0.001'
